import { Outfit, User, Rental } from '@/types';

export const MOCK_USERS: User[] = [
    {
        id: 'user-1',
        role: 'curator',
        displayName: 'Ashley',
        email: 'ashley@closetshare.in',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
        bio: 'Fashion enthusiast and style curator',
        stats: {
            outfitsCount: 24,
            rentalsCount: 105,
            rating: 4.8,
        },
        publicClosetSlug: 'ashley',
    },
    {
        id: 'user-2',
        role: 'curator',
        displayName: 'Jessica Parker',
        email: 'jessica@closetshare.in',
        avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
        bio: 'Vintage lover and sustainable fashion advocate',
        stats: {
            outfitsCount: 18,
            rentalsCount: 87,
            rating: 4.9,
        },
        publicClosetSlug: 'jessica',
    },
];

export const MOCK_OUTFITS: Outfit[] = [
    {
        id: 'outfit-1',
        curatorId: 'user-1',
        title: 'Burgundy Off-Shoulder Midi Dress',
        description: 'Elegant off-shoulder dress perfect for evening events. Made from premium silk blend fabric.',
        images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
        size: 'M',
        category: 'dress',
        perNightPrice: 450,
        securityDeposit: 1000,
        tags: ['Evening', 'Formal', 'Summer'],
        availability: { enabled: true, blockedDates: [] },
        status: 'active',
        stats: { rentalsCount: 12, rating: 4.8 },
        createdAt: Date.now() - 86400000 * 10,
        updatedAt: Date.now() - 86400000 * 10,
    },
    {
        id: 'outfit-2',
        curatorId: 'user-1',
        title: 'Emerald Green Maxi Dress',
        description: 'Stunning emerald green maxi dress with side slit.',
        images: ['https://images.unsplash.com/photo-1529139574466-a30232743490?auto=format&fit=crop&w=800&q=80'],
        size: 'L',
        category: 'dress',
        perNightPrice: 550,
        securityDeposit: 1200,
        tags: ['Party', 'Formal'],
        availability: { enabled: true, blockedDates: [] },
        status: 'active',
        stats: { rentalsCount: 8, rating: 4.9 },
        createdAt: Date.now() - 86400000 * 8,
        updatedAt: Date.now() - 86400000 * 8,
    },
    {
        id: 'outfit-3',
        curatorId: 'user-2',
        title: 'Black Leather Jacket',
        description: 'Classic black leather jacket for edgy looks.',
        images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
        size: 'M',
        category: 'outerwear',
        perNightPrice: 600,
        securityDeposit: 1500,
        tags: ['Casual', 'Edgy'],
        availability: { enabled: true, blockedDates: [] },
        status: 'active',
        stats: { rentalsCount: 5, rating: 5.0 },
        createdAt: Date.now() - 86400000 * 5,
        updatedAt: Date.now() - 86400000 * 5,
    },
];

export const MOCK_RENTALS: Rental[] = [
    {
        id: 'rental-1',
        outfitId: 'outfit-1',
        curatorId: 'user-1',
        renterUserId: 'user-3',
        renterEmail: 'jane.doe@example.com',
        renterName: 'Jane Doe',
        status: 'requested',
        startDate: Date.now() + 86400000 * 2,
        endDate: Date.now() + 86400000 * 5,
        nights: 3,
        deliveryAddress: {
            fullName: 'Jane Doe',
            phone: '+91 98765 43210',
            addressLine1: '123 Fashion Street',
            city: 'Mumbai',
            state: 'Maharashtra',
            zipCode: '400001',
        },
        pricing: {
            perNightPrice: 450,
            nights: 3,
            rentalFee: 1350,
            securityDeposit: 450,
            platformFee: 30,
            deliveryFee: 50,
            returnDeliveryFee: 50,
            total: 1930,
        },
        timeline: [{ status: 'requested', timestamp: Date.now() - 3600000 }],
        curatorEarnings: 1148,
        createdAt: Date.now() - 3600000,
        updatedAt: Date.now() - 3600000,
    },
];
